apiVersion: v1
kind: ConfigMap
metadata:
  name: user-order-service
  labels:
    app: user-order-service
data:
  application.properties: |-
    spring.application.name=user-order-service
    spring.profiles.active=k8s
    server.port=9090
    spring.cloud.kubernetes.reload.enabled=true 
    management.endpoint.restart.enabled = true
    server.compression.enabled=true
    
    external.url.service.user=http://127.0.0.1:9091/users
    external.url.service.order=http://127.0.0.1:19091/orders


